sudo: false
language: python
python:
    - 3.6
    - 3.7
    - 3.8

install:
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt

script:
    - python commands.py init en_US
    - python commands.py update
    - python commands.py compile
    - python commands.py gen-plugin-info
    - python test.py {}

after_success:
    - codecov
