sudo: false
language: python
python:
    - 3.6
    - 3.7
    - 3.8

before_install:
    - sudo apt-get update

install:
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt

script:
    - coverage run python commands.py init en_US
    - coverage run python commands.py update
    - coverage run python commands.py compile
    - coverage run python commands.py gen-plugin-info
    - coverage run python test.py {}

after_success:
    - codecov
